import customtkinter as ctk
ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("blue")
root=ctk.CTk()
root.geometry("600x500")
root.title("Expense Tracker")
login_frame=ctk.CTkFrame(root)
login_frame.pack(fill="both", expand=True)
container = ctk.CTkFrame(login_frame, width=350, height=350)
container.place(relx=0.5, rely=0.5, anchor="center")
ctk.CTkLabel(container, text="Login", font=("Arial", 26)).pack(pady=20)
login_user=ctk.CTkEntry(container, placeholder_text="Username", width=250)
login_user.pack(pady=10)
login_pass=ctk.CTkEntry(container, placeholder_text="Password", width=250, show="*")
login_pass.pack(pady=10)
login_btn=ctk.CTkButton(container, text="Login", width=100)
login_btn.pack(pady=20)
create_btn=ctk.CTkButton(container, text="Create Account", width=150)
create_btn.pack()
signup_frame=ctk.CTkFrame(root)
signup_container=ctk.CTkFrame(signup_frame, width=350, height=350)
signup_container.place(relx=0.5, rely=0.5, anchor="center")
def show_signup():
     login_frame.pack_forget()
     signup_frame.pack(fill="both", expand=True)
def show_login():
    signup_frame.pack_forget()
    login_frame.pack(fill="both", expand=True)
create_btn.configure(command=show_signup)
ctk.CTkLabel(signup_container, text="Create Account", font=("Arial", 26)).pack(pady=30)
signup_user=ctk.CTkEntry(signup_container, placeholder_text="Username", width=250)
signup_user.pack(pady=10)
signup_pass=ctk.CTkEntry(signup_container, placeholder_text="Password", width=250, show="*")
signup_pass.pack(pady=10)
signup_confirm=ctk.CTkEntry(signup_container, placeholder_text="Confirm Password", width=250, show="*")
signup_confirm.pack(pady=10)
create_btn=ctk.CTkButton(signup_container, text="Create Account", width=150)
create_btn.pack(pady=20)
back_btn=ctk.CTkButton(signup_container, text="Back to Login", width=150, command=show_login)
back_btn.pack()
root.mainloop()

